generated
symbolNames

	^ #( '"("' '")"' '"3×"' '"4×"' '">"' '"ABZ"' '"BAU"' '"HZL"' '"KWU"'
	     '"LAK"' '"MEA"' '"MZL"' '"N<"' '"REC"' '"RSP"' '"SL"' '"X"'
	     '"ZATU"' '"n("' '"n+"' '"|"' '"ₓ"' '<subscriptDigit>'
	     '<validLowercaseLetter>' '<validUppercaseLetter>'
	     '<digit>' '<modifier>' '<allograph>' '<compundOperator>'
	     'B e g i n' 'Start' 'SimpleSignName' '<validUppercaseLetter> ''letters''+'
	     '<subscriptDigit> ''number'' *' 'NumericSignName'
	     '<digit> ''digits'' +' 'SignListSignName' '<digit>+' 'SignName'
	     'SimpleSignValue' '<validLowercaseLetter> ''letters''+'
	     '<subscriptDigit> ''number''*' 'QualifiedSignName'
	     'QualifiedSignValue' 'SignValue' 'GraphemeRepetition'
	     'CompundSignName' 'GroupedSignName' 'E O F' 'error' )